### ISSUE TITLE
How do you get this?

### ISSUE THREAD

**Issue by yyellowsun** [SmithJson/NCUT-Presentation-Slides#2]
Some problem set and labs are missing.Please finish them.

**Comment by SmithJson** [comment]
> Some problem set and labs are missing.Please finish them.

I'm sorry, this warehouse is my junior year, and I really started to maintain it in the next semester. Many of the courses I set up here are handy, and the experiments have also been deleted. Then I don't know why the course selection system of North China University of technology can only view the courses of this semester, and can't download the previous course design. I can't help you, brother.

**Comment by yyellowsun** [comment]
> Some problem set and labs are missing.Please finish them.
> 
> I'm sorry, this warehouse is my junior year, and I really started to maintain it in the next semester. Many of the courses I set up here are handy, and the experiments have also been deleted. Then I don't know why the course selection system of North China University of technology can only view the courses of this semester, and can't download the previous course design. I can't help you, brother.
ok,plea
